scan_matcher:
  ros__parameters:
    global_frame_id: "map"
    robot_frame_id: "base_link"
    registration_method: "NDT"
    ndt_num_threads: 2
    trans_for_mapupdate: 1.0
    ndt_resolution: 1.0
    gicp_corr_dist_threshold: 5.0
    vg_size_for_input: 0.5
    vg_size_for_map: 0.1
    num_targeted_cloud: 40
    use_min_max_filter: true
    scan_min_range: 1.0
    scan_max_range: 30.0
    scan_period: 0.1
    map_publish_period: 5.0
    set_initial_pose: true
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_z: 0.0
    initial_pose_qx: 0.0
    initial_pose_qy: 0.0
    initial_pose_qz: 0.0
    initial_pose_qw: 1.0
    use_imu: false
    use_odom: true
    debug_flag: false

graph_based_slam:
  ros__parameters:
    registration_method: "NDT"
    ndt_num_threads: 2
    ndt_resolution: 0.5
    voxel_leaf_size: 0.1
    loop_detection_period: 10000
    threshold_loop_closure_score: 0.7
    distance_loop_closure: 100.0
    range_of_searching_loop_closure: 100.0
    search_submap_num: 5
    num_adjacent_pose_cnstraints: 5
    use_save_map_in_loop: true
    debug_flag: true

lidar_localization:
  ros__parameters:
    registration_method: "NDT_OMP"
    score_threshold: 2.0
    ndt_resolution: 0.5
    ndt_step_size: 0.1
    ndt_num_threads: 4
    transform_epsilon: 0.01
    voxel_leaf_size: 0.1
    scan_max_range: 30.0
    scan_min_range: 1.0
    scan_period: 0.1
    use_pcd_map: true
    map_path: "/home/administrator/experiment_files/map.pcd"
    set_initial_pose: false
    # initial_pose_x: 0.0
    # initial_pose_y: 0.0
    # initial_pose_z: 0.0
    # initial_pose_qx: 0.0
    # initial_pose_qy: 0.0
    # initial_pose_qz: 0.0
    # initial_pose_qw: 1.0
    use_odom: true
    use_imu: false
    enable_debug: true
    global_frame_id: map
    odom_frame_id: odom
    base_frame_id: base_link
