j100_0842:
  twist_server_node:
    ros__parameters:
      use_sim_time: True
      link_name: 'base_link'
      robot: 'j100'
      linear_scale: 1.0
      max_positive_linear_velocity: 1.0
      max_negative_linear_velocity: -1.0
