j100_0842:
  teleop_twist_joy_node:
    ros__parameters:
      use_sim_time: True
      axis_linear.x: 1
      scale_linear.x: 0.4
      scale_linear_turbo.x: 2.0
      axis_angular.yaw: 0
      scale_angular.yaw: 0.6
      scale_angular_turbo.yaw: 1.4
      enable_button: 4
      enable_turbo_button: 5
  joy_node:
    ros__parameters:
      use_sim_time: True
      deadzone: 0.1
      autorepeat_rate: 20.0
      dev: '/dev/input/ps4'
