imu_filter_node:
  ros__parameters:
    use_sim_time: False
    stateless: False
    use_mag: False
    publish_tf: False
    reverse_tf: False
    fixed_frame: 'odom'
    constant_dt: 0.0
    publish_debug_topics: False
    world_frame: 'enu'
    gain: 0.1
    zeta: 0.0
    mag_bias_x: 0.0
    mag_bias_y: 0.0
    mag_bias_z: 0.0
    orientation_stddev: 0.0
