microstrain_inertial_driver:
  ros__parameters:
    port: '/dev/microstrain_main'
    aux_port: '/dev/ttyACM1'
    baudrate: 115200
    debug: False
    diagnostics: False
    set_baud: False
    imu_frame_id: 'imu_1_link'
    gnss1_frame_id: 'gnss1_antenna_wgs84'
    gnss2_frame_id: 'gnss2_antenna_wgs84'
    filter_frame_id: 'sensor_wgs84'
    filter_child_frame_id: 'sensor'
    nmea_frame_id: 'nmea'
    poll_port: False
    poll_rate_hz: 1.0
    poll_max_tries: 60
    use_enu_frame: True
    device_setup: True
    save_settings: False
    use_device_timestamp: False
    use_ros_time: False
    raw_file_enable: False
    raw_file_include_support_data: False
    raw_file_directory: '/home/your_name'
    imu_data_rate: 100
    imu_raw_data_rate: -1
    imu_mag_data_rate: -1
    imu_gps_corr_data_rate: -1
    imu_overrange_status_data_rate: -1
    imu_orientation_cov: [0.0001, 0.0, 0.0, 0.0, 0.0001, 0.0, 0.0, 0.0, 0.0001]
    imu_linear_cov: [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
    imu_angular_cov: [0.01, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0, 0.0, 0.01]
    gnss1_data_rate: 2
    gnss1_nav_sat_fix_data_rate: -1
    gnss1_odom_data_rate: -1
    gnss1_time_reference_data_rate: -1
    gnss1_fix_info_data_rate: -1
    gnss1_sbas_info_data_rate: -1
    gnss1_rf_error_detection_data_rate: -1
    gnss1_antenna_offset: [0.0, -0.7, -1.0]
    gnss2_data_rate: 2
    gnss2_nav_sat_fix_data_rate: -1
    gnss2_odom_data_rate: -1
    gnss2_time_reference_data_rate: -1
    gnss2_fix_info_data_rate: -1
    gnss2_sbas_info_data_rate: -1
    gnss2_rf_error_detection_data_rate: -1
    gnss2_antenna_offset: [0.0, 0.7, -1.0]
    rtk_dongle_enable: False
    rtk_data_rate: 1
    rtk_status_data_rate: 1
    subscribe_rtcm: False
    rtcm_topic: '/rtcm'
    publish_nmea: False
    filter_data_rate: 10
    filter_status_data_rate: -1
    filter_heading_data_rate: -1
    filter_heading_state_data_rate: -1
    filter_odom_data_rate: -1
    filter_imu_data_rate: -1
    filter_relative_odom_data_rate: -1
    filter_aiding_status_data_rate: -1
    filter_antenna_offset_correction_data_rate: -1
    filter_gnss_dual_antenna_data_rate: -1
    filter_aiding_measurement_summary_data_rate: -1
    filter_sensor2vehicle_frame_selector: 1
    filter_sensor2vehicle_frame_transformation_euler: [0.0, 0.0, 0.0]
    filter_sensor2vehicle_frame_transformation_matrix: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    filter_sensor2vehicle_frame_transformation_quaternion: [0.0, 0.0, 0.0, 1.0]
    filter_reset_after_config: True
    filter_auto_init: True
    filter_declination_source: 2
    filter_declination: 0.23
    filter_heading_source: 1
    filter_dynamics_mode: 1
    filter_use_compensated_accel: True
    filter_velocity_zupt_topic: '/moving_vel'
    filter_angular_zupt_topic: '/moving_ang'
    filter_velocity_zupt: True
    filter_angular_zupt: True
    filter_adaptive_level: 2
    filter_adaptive_time_limit_ms: 15000
    filter_enable_gnss_pos_vel_aiding: True
    filter_enable_gnss_heading_aiding: True
    filter_enable_altimeter_aiding: False
    filter_enable_odometer_aiding: False
    filter_enable_magnetometer_aiding: False
    filter_enable_external_heading_aiding: False
    filter_enable_external_gps_time_update: False
    filter_external_gps_time_topic: '/external_gps_time'
    gps_leap_seconds: 18.0
    filter_external_speed_topic: '/external_speed'
    filter_vel_in_vehicle_frame: True
    filter_lever_arm_offset: [0.0, 0.0, 0.0]
    enable_hardware_odometer: False
    odometer_scaling: 0.0
    odometer_uncertainty: 0.0
    gpio_config: False
    gpio1_feature: 0
    gpio1_behavior: 0
    gpio1_pin_mode: 0
    gpio2_feature: 0
    gpio2_behavior: 0
    gpio2_pin_mode: 0
    gpio3_feature: 0
    gpio3_behavior: 0
    gpio3_pin_mode: 0
    gpio4_feature: 0
    gpio4_behavior: 0
    gpio4_pin_mode: 0
    filter_init_condition_src: 0
    filter_auto_heading_alignment_selector: 1
    filter_init_reference_frame: 2
    filter_init_position: [0.0, 0.0, 0.0]
    filter_init_velocity: [0.0, 0.0, 0.0]
    filter_init_attitude: [0.0, 0.0, 0.0]
    filter_relative_position_config: False
    filter_relative_position_frame: 2
    filter_relative_position_source: 1
    filter_relative_position_ref: [0.0, 0.0, 0.01]
    filter_speed_lever_arm: [0.0, 0.0, 0.0]
    filter_enable_wheeled_vehicle_constraint: False
    filter_enable_vertical_gyro_constraint: False
    filter_enable_gnss_antenna_cal: True
    filter_gnss_antenna_cal_max_offset: 0.1
    filter_pps_source: 1
    sbas_enable: True
    sbas_enable_ranging: False
    sbas_enable_corrections: True
    sbas_apply_integrity: False
    nmea_message_config: False
    nmea_message_allow_duplicate_talker_ids: False
    imu_nmea_prkr_data_rate: 0
    gnss1_nmea_talker_id: 1
    gnss1_nmea_gga_data_rate: 0
    gnss1_nmea_gll_data_rate: 0
    gnss1_nmea_gsv_data_rate: 0
    gnss1_nmea_rmc_data_rate: 0
    gnss1_nmea_vtg_data_rate: 0
    gnss1_nmea_hdt_data_rate: 0
    gnss1_nmea_zda_data_rate: 0
    gnss2_nmea_talker_id: 2
    gnss2_nmea_gga_data_rate: 0
    gnss2_nmea_gll_data_rate: 0
    gnss2_nmea_gsv_data_rate: 0
    gnss2_nmea_rmc_data_rate: 0
    gnss2_nmea_vtg_data_rate: 0
    gnss2_nmea_hdt_data_rate: 0
    gnss2_nmea_zda_data_rate: 0
    filter_nmea_talker_id: 3
    filter_nmea_gga_data_rate: 0
    filter_nmea_gll_data_rate: 0
    filter_nmea_rmc_data_rate: 0
    filter_nmea_hdt_data_rate: 0
    filter_nmea_prka_data_rate: 0
