sensors/camera_0:
  ros__parameters:
    # camera_name: 'camera_0'
    # serial_no: '341622073339'
    usb_port_id: ''
    device_type: 'd435'
    config_file: ''
    unite_imu_method: 0
    json_file_path: ''
    log_level: 'info'
    output: 'screen'
    depth_module.depth_profile: '424,240,6' #Steve mod: reduce resolution & fps
    enable_depth: True
    rgb_camera.color_profile: '424,240,6' #Steve mod: reduce resolution & fps
    rgb_camera.enable_auto_exposure: True
    enable_color: True
    enable_infra1: False
    enable_infra2: False
    infra_rgb: False
    enable_fisheye1: True
    enable_fisheye2: True
    enable_confidence: True
    gyro_fps: 0
    accel_fps: 0
    enable_gyro: False
    enable_accel: False
    enable_pose: True
    pose_fps: 200
    pointcloud.enable: True
    pointcloud.stream_filter: 0 #Steve mod: remove color info
    pointcloud.stream_index_filter: 0
    enable_sync: False
    align_depth.enable: False
    colorizer.enable: False
    clip_distance: -2.0
    linear_accel_cov: 0.01
    initial_reset: False
    allow_no_texture_points: False
    pointcloud.ordered_pc: False
    tf_publish_rate: 0.0
    diagnostics_period: 0.0
    decimation_filter.enable: True
    decimation_filter.filter_magnitude: 6 #Steve mod: reduce size
    rosbag_filename: ''
    depth_module.exposure.1: 7500
    depth_module.gain.1: 16
    depth_module.exposure.2: 1
    depth_module.gain.2: 16
    depth_module.exposure: 8500
    depth_module.hdr_enabled: False
    depth_module.enable_auto_exposure: True
    hdr_merge.enable: False
    wait_for_device_timeout: -1.0
    reconnect_timeout: 6.0
