ekf_node:
  ros__parameters:
    odom_frame: 'odom'
    base_link_frame: 'base_link'
    world_frame: 'odom'
    publish_tf: True
    two_d_mode: True
    use_sim_time: False
    frequency: 50.0
    odom0: 'platform/odom'
    odom0_config: [False, False, False, False, False, False, True, True, False, False, False, False, False, False, False]
    odom0_differential: False
    odom0_queue_size: 10
    # Steve mod: remove built in IMU, use fancy IMU instead
    # imu0: 'sensors/imu_0/data'
    # imu0_config: [False, False, False, False, False, False, False, False, False, False, False, True, True, False, False]
    # imu0_differential: False
    # imu0_queue_size: 10
    # imu0_remove_gravitational_acceleration: True
    imu0: 'sensors/imu_1/data'
    imu0_config: [False, False, False, False, False, False, False, False, False, False, False, True, False, False, False]
    imu0_differential: False
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: True

# For 3D: IMU include roll, pitch; two_d_mode: false; odom0 Z-vel; odom1 of odometry source (optional)
