controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: False

    joint_state_broadcaster.type: 'joint_state_broadcaster/JointStateBroadcaster'
    platform_velocity_controller.type: 'diff_drive_controller/DiffDriveController'

platform_velocity_controller:
  ros__parameters:
    use_sim_time: False
    left_wheel_names: [ 'front_left_wheel_joint', 'rear_left_wheel_joint' ]
    right_wheel_names: [ 'front_right_wheel_joint', 'rear_right_wheel_joint' ]

    wheel_separation: 0.37559
    wheels_per_side: 1
    wheel_radius: 0.095
    wheel_separation_multiplier: 1.5
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: 'odom'
    base_frame_id: 'base_link'
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: false
    enable_odom_tf: false
    tf_frame_prefix_enable: false

    cmd_vel_timeout: 0.5
    use_stamped_vel: true
    #velocity_rolling_window_size: 10

    # Preserve turning radius when limiting speed/acceleration/jerk
    preserve_turning_radius: true

    # Publish limited velocity
    publish_limited_velocity: true

    # Publish wheel data
    publish_wheel_data: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.max_velocity: 2.0
    linear.x.min_velocity: -2.0
    linear.x.max_acceleration: 2.0
    linear.x.max_deceleration: -4.0
    linear.x.max_acceleration_reverse: -2.0
    linear.x.max_deceleration_reverse: 4.0
    linear.x.max_jerk: .NAN
    linear.x.min_jerk: .NAN

    angular.z.max_velocity: 4.0
    angular.z.min_velocity: -4.0
    angular.z.max_acceleration: 4.0
    angular.z.max_deceleration: -4.0
    angular.z.max_acceleration_reverse: -4.0
    angular.z.max_deceleration_reverse: 4.0
    angular.z.max_jerk: .NAN
    angular.z.min_jerk: .NAN
