teleop_twist_joy_node:
  ros__parameters:
    use_sim_time: False
    axis_linear.x: 1
    axis_angular.yaw: 0

    enable_button: 4
    scale_linear.x: 0.5
    scale_angular.yaw: 1.4

    enable_turbo_button: 5
    scale_linear_turbo.x: 2.0
    scale_angular_turbo.yaw: 4.0

joy_node:
  ros__parameters:
    use_sim_time: False
    deadzone: 0.1
    autorepeat_rate: 20.0
    dev: '/dev/input/ps4'
