twist_mux:
  ros__parameters:
    use_sim_time: False
    topics.joy.topic: 'joy_teleop/cmd_vel'
    topics.joy.timeout: 0.5
    topics.joy.priority: 10
    topics.rc.topic: 'rc_teleop/cmd_vel'
    topics.rc.timeout: 0.5
    topics.rc.priority: 12
    topics.external.topic: 'cmd_vel'
    topics.external.timeout: 0.5
    topics.external.priority: 1
    locks.e_stop.topic: 'platform/emergency_stop'
    locks.e_stop.timeout: 0.0
    locks.e_stop.priority: 255
    locks.e_stop.topic: 'joy_teleop/emergency_stop'
    locks.e_stop.timeout: 0.0
    locks.e_stop.priority: 200
