#!/usr/bin/env bash

file_path="$HOME/colcon_ws/src/ona01_jackal/ona01_bringup/config"
file_name="robot"
file_extension="yaml"

the_file="$file_path/$file_name.$file_extension"
#symlink_file="$file_name-symlink.$file_extension"
symlink_file="$file_name.$file_extension"

if [[ "$1" == "robot" ]]; then
  target_path="/etc/clearpath"
elif [[ "$1" != "robot" && -n "$1" ]]; then
  target_path="$1"
else
  target_path="$HOME/clearpath"
fi

[[ -n "$2" ]] && symlink_file="$2"

if [[ -f $the_file ]]; then
  if [[ -d "$target_path" ]]; then
    ln -s "$the_file" "$target_path/$symlink_file"
    if [ $? -eq 0 ]; then
      echo -e "\033[32m$symlink_file installed to $target_path\e[0m"
      ls -l $target_path/$symlink_file
    else
      echo -e "\033[31mFailed to install $symlink_file file to $target_path\e[0m"
    fi
  else
    echo -e "Directory \033[31m$target_path\e[0m does not exist"
  fi
else
  echo -e "\033[31m$the_file\e[0m does not exist"
fi

